-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            noise = 0.011,
            passes = 1,
        },
        dim_around = 0.4,
        rounding = 10,
    },
    general = {
        border_size = 2,
        col = {
            active_border = "0xffffbe6f",
        },
        gaps_in = 1,
        gaps_out = 6,
        resize_on_border = true,
    },
})

-- Bezier curves
hl.curve("specialWorkSwitch", { type = "bezier", points = { {0.05, 0.7}, {0.1, 1.0} } })

-- Animations
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 8.0,
    bezier = "specialWorkSwitch",
})

-- Monitors
hl.monitor({
    output = "DP-6",
    disabled = false,
    mode = "1920x1080@179.96Hz",
    position = "3500x1080",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "DP-7",
    disabled = false,
    mode = "1920x1080@179.96Hz",
    position = "5460x1080",
    scale = 1,
    cm = "srgb",
})
hl.monitor({
    output = "HDMI-A-2",
    disabled = false,
    mode = "1600x900@60.00Hz",
    position = "7430x1260",
    scale = 1,
    cm = "srgb",
})
